apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lhin0wjrt-go 
  janus-idp.io/tekton: lhin0wjrt-go
  backstage.io/kubernetes-id: lhin0wjrt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lhin0wjrt-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml