apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lhin0wjrt-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lhin0wjrt-go 
  name: lhin0wjrt-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lhin0wjrt-go 
